# Mining the fine print - Privacy Scoring {#Fintech-Privacy-Scoring}

#### Keywords {-}

FinTech Privacy, Text Mining, Natural Language

## FinTech innovations create new privacy challenges

FinTech companies leverage new technology to create new and better financial services for both consumers and businesses. These emerging technologies are disrupting investment management, insurance and lending industries creating better user experiences reducing friction. FinTech companies use machine learning and user information to personalize traditional financial services. 
When users signup for FinTech applications, the application developers request users to provide access personal information like social security information, banking transactions, savings, social media handles and other mobile data. There are many cases where the applications monitor extremely private information like location and voice call information which are not needed to personalize the applications. Even though users agree to terms and conditions of using the applciations, the privacy policies are embedded in the fine text of terms and conditions. The privacy policy conformance to user privacy regulations like COPPA, GDPR is difficult to comprehend. Our project intends to develop an app which can be installed on smartphone and will monitor the data access and usage by various FinTech applications. We use a staggered approach to develop our project and the first step is a detailed study of privacy policies of top 500 FinTech applications on App Store & Google Play. 


## Privacy awareness levels and regulation compliance is all over the place

To develop the study, we conducted user interviews with users and FinTech startups to understand the key objectives of each stakeholder. The following section provides an overview of user segments and solutions:

#### Key user segments and needs:{-}
a) Users: {-}:

Users download the apps and use them regularly. They have heterogeneous privacy awareness levels but unanimously like the idea of being aware of data being used by other FinTech apps. 

b) FinTech Startups:{-}

Product managers and compliance teams want to be aware of the new privacy regulations and want to benchmark their app privacy with other apps on the App store. 

c) Regulators:{-}

Regulators don't have an automated process to identify missing privacy policies and inconsistencies of policies across the top 500 applications. They also would like to track when privacy policies change for specific applications and would like to review if they conform to various regulations. 

To further refine our scope, we will limit our study to work with regulators to review our study findings and develop data privacy scoring models. We plan to use the following research methodology:

a) Scope of FinTech Apps:{-} 

We are using data from Crunchbase, Google Play and Apple App Store to extract most funded and most downloaded FinTech Apps. 

b) Privacy policy scraping:{-} 
Based on the list of FinTech Apps, we retrieve the privacy policies from application websites, Google play pages and Apple app store pages. 

c) Privacy policy text mining:{-} 
We will run advanced text mining algorithms to compare to human annotated privacy policy data. rank the privacy policy and data privacy information of all the applications. 

d) Results Validation:{-} 
We will provide the results of text mining to regulators to validate our results and provide feedback on our text mining algorithms. 

e) Feedback & Changes:{-} 
Once we get detailed feedback from the regulators, we plan to conduct additional user interviews with FinTech startups who are not in compliance. 


## Privacy is not a "Feature":

After completing the study, we plan to move forward to build our application.  We will offer initial solution to regulators to monitor all the FinTech apps registered in United States. This would allow regulators to coach FinTech startups on improving their compliance to privacy regulations as well as develop new regulations to support the innovations. 

We also want to develop privacy scoring models to assist FinTech startups to develop better privacy aware products. This will actively allow startups to focus on products which are user privacy compliant reducing possible legal and reputational risks. 

Next we plan to provide this to users to download on their smart phone and monitor data privacy concerns for their FinTech applications and over time allow them to track all mobile applications.  We also intend to extend the analysis to Amazon and windows applications in the future. 


## References:{-}
a) J. Lin, B. Liu, N. Sadeh, and J.I. Hong, Modeling Users’ Mobile App Privacy Preferences: Restoring Usability in a Sea of Permission Settings, 2014 ACMSymposium on Usable Security and Privacy (SOUPS 2014), July 2014.

b) B. Liu, J. Lin, N. Sadeh, Reconciling Mobile App Privacy and Usability on Smartphones: Could User Privacy Profiles Help?, 23rd Interntional Conference on the World Wide Web (WWW 2014).

c) A. Sinha, Y. Li, and L. Bauer, “What you want is not what you get: Predicting sharing policies for text-based content on Facebook,” In Proc. AISec, 2013.

d) Peter Story, Sebastian Zimmeck, Norman Sadeh, "Which Apps have Privacy Policies?", Carnegie Mellon University Technical Report CMU-ISR-18-100, Institute for Software Research, School of Computer Science, Feb 2018

e) Frederick Liu, Shomir Wilson, Peter Story, Sebastian Zimmeck and Norman Sadeh, "Towards Automatic Classification of Privacy Policy Text", Carnegie Mellon University Technical Report CMU‐ISR‐17‐118 and CMU‐LTI‐17‐010, Institute for Software Research and Language Technologies Institute, School of Computer Science, Dec 2017
